services:
    web:
        image: moemoev/mybgapp.web
        deploy:
            replicas: 5
        ports:
            - 8080:80
        volumes:
          - "/home/vagrant/mybgapp/web:/var/www/html:ro"
        networks:
            - app-network
    db:
        image: moemoev/mybgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password
        secrets:
          -db_root_password
secrets:
  db_root_password:
      external: true
networks:
    app-network:
